CREATE TABLE K_FORSENDELSE_METADATA_TYPE
(
    K_FORSENDELSE_METADATA_TYPE VARCHAR2(128 CHAR) PRIMARY KEY,
    DEKODE                      VARCHAR2(128 CHAR) NOT NULL,
    DATO_OPPRETTET              TIMESTAMP          NOT NULL,
    OPPRETTET_AV                VARCHAR2(128 CHAR) NOT NULL,
    DATO_ENDRET                 TIMESTAMP,
    ENDRET_AV                   VARCHAR2(128 CHAR)
);

INSERT INTO K_FORSENDELSE_METADATA_TYPE(K_FORSENDELSE_METADATA_TYPE, DEKODE, DATO_OPPRETTET, OPPRETTET_AV)
SELECT 'DPO_AVTALEMELDING',
       'DPO Avtalemelding',
       systimestamp,
       'MMA-7741'
FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM K_FORSENDELSE_METADATA_TYPE WHERE K_FORSENDELSE_METADATA_TYPE = 'DPO_AVTALEMELDING');

INSERT INTO K_FORSENDELSE_METADATA_TYPE(K_FORSENDELSE_METADATA_TYPE, DEKODE, DATO_OPPRETTET, OPPRETTET_AV)
SELECT 'DPO_ARKIVMELDING',
       'DPO Arkivmelding',
       systimestamp,
       'MMA-7741'
FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM K_FORSENDELSE_METADATA_TYPE WHERE K_FORSENDELSE_METADATA_TYPE = 'DPO_ARKIVMELDING');


ALTER TABLE DOKUMENT_INFO
    ADD (
        FORSENDELSE_METADATA VARCHAR2(4000 CHAR),
        K_FORSENDELSE_METADATA_TYPE VARCHAR2(128 CHAR)
            CONSTRAINT FK_FORSENDELSE_METADATA_TYPE REFERENCES K_FORSENDELSE_METADATA_TYPE (K_FORSENDELSE_METADATA_TYPE)
        );