CREATE TABLE T_K_FORS_METADATA_TYPE(
    K_FORS_METADATA_TYPE	VARCHAR2(128)	NOT NULL,
    DEKODE	                VARCHAR(128)	NOT NULL,
    DATO_OPPRETTET	        TIMESTAMP(6)	NOT NULL,
    OPPRETTET_AV	        VARCHAR(128)	NOT NULL,
    DATO_ENDRET	            TIMESTAMP(6)	NULL,
    ENDRET_AV	            VARCHAR(128)	NULL,
    CONSTRAINT XPKK_FORS_METADATA_TYPE PRIMARY KEY (K_FORS_METADATA_TYPE)
);

INSERT INTO T_K_FORS_METADATA_TYPE(K_FORS_METADATA_TYPE, DEKODE, DATO_OPPRETTET, OPPRETTET_AV)
SELECT
    'DPO_AVTALEMELDING',
    'DPO Avtalemelding',
    systimestamp,
    'MMA-7741'
FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM T_K_FORS_METADATA_TYPE WHERE K_FORS_METADATA_TYPE = 'DPO_AVTALEMELDING');

INSERT INTO T_K_FORS_METADATA_TYPE(K_FORS_METADATA_TYPE, DEKODE, DATO_OPPRETTET, OPPRETTET_AV)
SELECT
    'DPO_ARKIVMELDING',
    'DPO Arkivmelding',
    systimestamp,
    'MMA-7741'
FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM T_K_FORS_METADATA_TYPE WHERE K_FORS_METADATA_TYPE = 'DPO_ARKIVMELDING');


ALTER TABLE DOKUMENT_INFO ADD (
    FORSENDELSE_METADATA    VARCHAR2(4000)  NULL,
    K_FORS_METADATA_TYPE  VARCHAR2(128)     NULL
    );

ALTER TABLE DOKUMENT_INFO
    ADD CONSTRAINT R_FORS_METADATA_TYPE
        FOREIGN KEY (K_FORS_METADATA_TYPE)
            REFERENCES T_K_FORS_METADATA_TYPE;