CREATE SEQUENCE POSTADRESSE_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE;

ALTER TABLE DOKUMENT_INFO
ADD postadresse_id NUMBER(11);

CREATE INDEX XIE3DOKUMENT_INFO ON DOKUMENT_INFO
(postadresse_id ASC);

CREATE TABLE K_LANDKODE_POST_DEST
(
  k_landkode       VARCHAR2(20) NOT NULL,
  post_dest      VARCHAR2(20) NULL,
  opprettet_dato TIMESTAMP    NOT NULL,
  opprettet_av   VARCHAR2(20) NOT NULL,
  endret_dato    TIMESTAMP    NULL,
  endret_av      VARCHAR2(20) NULL
);

CREATE UNIQUE INDEX XPKK_LANDKODE_POST_DEST ON K_LANDKODE_POST_DEST
(k_landkode ASC);

ALTER TABLE K_LANDKODE_POST_DEST
ADD CONSTRAINT XPKK_LANDKODE_POST_DEST PRIMARY KEY (k_landkode);

CREATE TABLE POSTADRESSE
(
  postadresse_id NUMBER(11)    NOT NULL,
  adresselinje1  VARCHAR2(200) NOT NULL,
  adresselinje2  VARCHAR2(200) NULL,
  adresselinje3  VARCHAR2(200) NULL,
  postnummer     VARCHAR2(20)  NULL,
  poststed       VARCHAR2(200) NULL,
  k_landkode     VARCHAR2(20)  NOT NULL,
  opprettet_dato TIMESTAMP     NOT NULL,
  opprettet_av   VARCHAR2(20)  NOT NULL,
  endret_dato    TIMESTAMP     NULL,
  endret_av      VARCHAR2(20)  NULL,
  versjon        NUMBER(9)     NOT NULL
);

CREATE UNIQUE INDEX XPKPOSTADRESSE ON POSTADRESSE
(postadresse_id ASC);

ALTER TABLE POSTADRESSE
ADD CONSTRAINT XPKPOSTADRESSE PRIMARY KEY (postadresse_id);

ALTER TABLE POSTADRESSE
ADD (CONSTRAINT R_39 FOREIGN KEY (k_landkode) REFERENCES K_LANDKODE_POST_DEST (k_landkode));

ALTER TABLE DOKUMENT_INFO
ADD (CONSTRAINT R_40 FOREIGN KEY (postadresse_id) REFERENCES POSTADRESSE (postadresse_id));
