CREATE TABLE DISTRIBUER_JOURNALPOST_INFO
(
    JOURNALPOST_ID NUMBER(19)    NOT NULL PRIMARY KEY,
    BESTILLING_ID  VARCHAR2(128 CHAR)   NOT NULL,
    OPPRETTET_DATO TIMESTAMP NOT NULL,
    OPPRETTET_AV   VARCHAR2(512 CHAR)  NOT NULL,
);