CREATE TABLE DISTRIBUER_JOURNALPOST_INFO
(
    JOURNALPOST_ID NUMBER(19)    NOT NULL,
    BESTILLING_ID  VARCHAR2(50)   NOT NULL,
    OPPRETTET_DATO TIMESTAMP NOT NULL,
    OPPRETTET_AV   VARCHAR2(512 CHAR)  NOT NULL,
    ENDRET_DATO    TIMESTAMP,
    ENDRET_AV      VARCHAR2(512 CHAR),
    VERSJON        NUMBER(9) NOT NULL
);

CREATE UNIQUE INDEX XPK_DISTRIBUER_JOURNALPOST_INFO ON DISTRIBUER_JOURNALPOST_INFO
    (JOURNALPOST_ID ASC);

ALTER TABLE DISTRIBUER_JOURNALPOST_INFO
    ADD CONSTRAINT XPK_DISTRIBUER_JOURNALPOST_INFO PRIMARY KEY (JOURNALPOST_ID);
