spring.main.banner_mode=off
spring.jpa.open-in-view=false

# server
server.shutdown=graceful
server.error.include-message=always

# actuators
management.endpoints.web.exposure.include=prometheus,health

# Database
spring.jpa.properties.hibernate.session_factory.interceptor=no.nav.dokdistadmin.domain.util.ChangeStampInterceptor
spring.jpa.properties.hibernate.query.in_clause_parameter_padding=true
spring.jpa.properties.hibernate.jdbc.fetch_size=100

# flyway
spring.flyway.enabled=true
spring.flyway.table=schema_version
spring.flyway.out-of-order=false
spring.flyway.validate-on-migrate=false
