logging.config=classpath:logback-spring.xml
spring.main.banner_mode=off
# server
server.shutdown=graceful
server.tomcat.threads.max=200
server.error.include-message=always
# actuators
management.endpoints.web.exposure.include=prometheus,health
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true

#db
spring.jpa.open-in-view=false
spring.transaction.default-timeout=300s
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
spring.jpa.properties.hibernate.ejb.interceptor=no.nav.dokdistadmin.core.interceptor.ChangeStampInterceptor
