logging.config=classpath:logback-spring.xml
spring.main.banner_mode=off
# server
server.shutdown=graceful
server.tomcat.threads.min-spare=10
server.tomcat.threads.max=200
server.error.include-message=always
# actuators
management.endpoints.web.exposure.include=prometheus,health
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true