--Dokumentdistribusjon tabeller

CREATE SEQUENCE DISTRIBUSJON_INFO_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE DOKUMENT_INFO_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE FIL_INFO_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE;

CREATE TABLE DIST_INFO_FIL_INFO
(
	distribusjon_info_id NUMBER(11) NOT NULL ,
	fil_info_id          NUMBER(11) NOT NULL 
);

CREATE UNIQUE INDEX XPKDIST_INFO_FIL_INFO ON DIST_INFO_FIL_INFO
(distribusjon_info_id   ASC,fil_info_id   ASC);

ALTER TABLE DIST_INFO_FIL_INFO
	ADD CONSTRAINT  XPKDIST_INFO_FIL_INFO PRIMARY KEY (distribusjon_info_id,fil_info_id);

CREATE INDEX XIF1DIST_INFO_FIL_INFO ON DIST_INFO_FIL_INFO
(distribusjon_info_id   ASC);

CREATE INDEX XIF2DIST_INFO_FIL_INFO ON DIST_INFO_FIL_INFO
(fil_info_id   ASC);

CREATE TABLE DISTRIBUSJON_INFO
(
	distribusjon_info_id NUMBER(11) NOT NULL ,
	distribusjon_id      VARCHAR2(20) NOT NULL ,
	avtale_referanse     VARCHAR2(20) NULL ,
	produksjon_dato      TIMESTAMP NULL ,
	distribusjon_dato    TIMESTAMP NOT NULL ,
	opprettet_dato       TIMESTAMP NOT NULL ,
	opprettet_av         VARCHAR2(20) NOT NULL ,
	endret_dato          TIMESTAMP NULL ,
	endret_av            VARCHAR2(20) NULL ,
	k_dist_status        VARCHAR2(20) NOT NULL ,
	k_modus              VARCHAR2(20) NOT NULL ,
	k_kanal_behandling   VARCHAR2(20) NULL ,
	k_post_dest          VARCHAR2(20) NULL ,
	k_dist_kanal         VARCHAR2(20) NOT NULL ,
	versjon              NUMBER(9) NOT NULL ,
	eff_tidligst_dato    DATE NULL ,
	eff_senest_dato      DATE NULL ,
	bekr_mottatt_dato    TIMESTAMP NULL 
);

CREATE UNIQUE INDEX XPKDISTRIBUSJON_INFO ON DISTRIBUSJON_INFO
(distribusjon_info_id   ASC);

ALTER TABLE DISTRIBUSJON_INFO
	ADD CONSTRAINT  XPKDISTRIBUSJON_INFO PRIMARY KEY (distribusjon_info_id);

CREATE INDEX XIF1DISTRIBUSJON_INFO ON DISTRIBUSJON_INFO
(k_dist_kanal   ASC);

CREATE INDEX XIF2DISTRIBUSJON_INFO ON DISTRIBUSJON_INFO
(k_dist_status   ASC);

CREATE INDEX XIF3DISTRIBUSJON_INFO ON DISTRIBUSJON_INFO
(k_modus   ASC);

CREATE INDEX XIF4DISTRIBUSJON_INFO ON DISTRIBUSJON_INFO
(k_kanal_behandling   ASC);

CREATE INDEX XIF5DISTRIBUSJON_INFO ON DISTRIBUSJON_INFO
(k_post_dest   ASC);

CREATE TABLE DOK_INFO_FIL_INFO
(
	dokument_info_id     NUMBER(11) NOT NULL ,
	fil_info_id          NUMBER(11) NOT NULL 
);

CREATE UNIQUE INDEX XPKDOK_INFO_FIL_INFO ON DOK_INFO_FIL_INFO
(dokument_info_id   ASC,fil_info_id   ASC);

ALTER TABLE DOK_INFO_FIL_INFO
	ADD CONSTRAINT  XPKDOK_INFO_FIL_INFO PRIMARY KEY (dokument_info_id,fil_info_id);

CREATE INDEX XIF1DOK_INFO_FIL_INFO ON DOK_INFO_FIL_INFO
(dokument_info_id   ASC);

CREATE INDEX XIF2DOK_INFO_FIL_INFO ON DOK_INFO_FIL_INFO
(fil_info_id   ASC);

CREATE TABLE DOKUMENT_INFO
(
	dokument_info_id     NUMBER(11) NOT NULL ,
	dokument_id          VARCHAR2(40) NOT NULL ,
	mottaker_id          VARCHAR2(20) NULL ,
	arkivkode            VARCHAR2(30) NULL ,
	avstemt_arkiv_dato   TIMESTAMP NULL ,
	antall_sider         NUMBER(9) NULL ,
	antall_ark           NUMBER(9) NULL ,
	opprettet_dato       TIMESTAMP NOT NULL ,
	opprettet_av         VARCHAR2(20) NOT NULL ,
	endret_dato          TIMESTAMP NULL ,
	endret_av            VARCHAR2(20) NULL ,
	distribusjon_info_id NUMBER(11) NOT NULL ,
	k_dokument_status    VARCHAR2(20) NOT NULL ,
	k_fagomrade          VARCHAR2(20) NULL ,
	k_best_fagsystem     VARCHAR2(20) NULL ,
	k_arkiv_system       VARCHAR2(20) NULL ,
	versjon              NUMBER(9) NOT NULL ,
	ekspedert_dato       TIMESTAMP NULL ,
	mottaker_navn        VARCHAR2(50) NULL ,
	brevkode             VARCHAR2(20) NULL ,
	k_brev_prod_app      VARCHAR2(20) NULL 
);

CREATE UNIQUE INDEX XPKDOKUMENT_INFO ON DOKUMENT_INFO
(dokument_info_id   ASC);

ALTER TABLE DOKUMENT_INFO
	ADD CONSTRAINT  XPKDOKUMENT_INFO PRIMARY KEY (dokument_info_id);

CREATE INDEX XIF1DOKUMENT_INFO ON DOKUMENT_INFO
(distribusjon_info_id   ASC);

CREATE INDEX XIF2DOKUMENT_INFO ON DOKUMENT_INFO
(k_dokument_status   ASC);

CREATE INDEX XIF3DOKUMENT_INFO ON DOKUMENT_INFO
(k_fagomrade   ASC);

CREATE INDEX XIF4DOKUMENT_INFO ON DOKUMENT_INFO
(k_best_fagsystem   ASC);

CREATE INDEX XIF5DOKUMENT_INFO ON DOKUMENT_INFO
(k_arkiv_system   ASC);

CREATE INDEX XIF6DOKUMENT_INFO ON DOKUMENT_INFO
(k_brev_prod_app   ASC);

CREATE TABLE FIL_INFO
(
	fil_info_id          NUMBER(11) NOT NULL ,
	filnavn              VARCHAR2(35) NOT NULL ,
	mottatt_dato         TIMESTAMP NULL ,
	sendt_dato           TIMESTAMP NULL ,
	k_fil_type           VARCHAR2(20) NOT NULL ,
	k_komm_retning       VARCHAR2(20) NOT NULL ,
	k_fil_status         VARCHAR2(20) NOT NULL ,
	k_kilde_type         VARCHAR2(20) NOT NULL ,
	opprettet_dato       TIMESTAMP NOT NULL ,
	opprettet_av         VARCHAR2(20) NOT NULL ,
	endret_dato          TIMESTAMP NULL ,
	endret_av            VARCHAR2(20) NULL ,
	versjon              NUMBER(9) NOT NULL 
);

CREATE UNIQUE INDEX XPKFIL_INFO ON FIL_INFO
(fil_info_id   ASC);

ALTER TABLE FIL_INFO
	ADD CONSTRAINT  XPKFIL_INFO PRIMARY KEY (fil_info_id);

CREATE INDEX XIF1FIL_INFO ON FIL_INFO
(k_fil_type   ASC);

CREATE INDEX XIF2FIL_INFO ON FIL_INFO
(k_komm_retning   ASC);

CREATE INDEX XIF3FIL_INFO ON FIL_INFO
(k_fil_status   ASC);

CREATE INDEX XIF4FIL_INFO ON FIL_INFO
(k_kilde_type   ASC);

CREATE TABLE K_ARKIV_SYSTEM
(
	k_arkiv_system       VARCHAR2(20) NOT NULL ,
	dekode               VARCHAR2(200) NOT NULL ,
	opprettet_dato       TIMESTAMP NOT NULL ,
	opprettet_av         VARCHAR2(20) NOT NULL ,
	endret_dato          TIMESTAMP NULL ,
	endret_av            VARCHAR2(20) NULL 
);

CREATE UNIQUE INDEX XPKK_ARKIV_SYSTEM ON K_ARKIV_SYSTEM
(k_arkiv_system   ASC);

ALTER TABLE K_ARKIV_SYSTEM
	ADD CONSTRAINT  XPKK_ARKIV_SYSTEM PRIMARY KEY (k_arkiv_system);

CREATE TABLE K_BEST_FAGSYSTEM
(
	k_best_fagsystem     VARCHAR2(20) NOT NULL ,
	dekode               VARCHAR2(200) NOT NULL ,
	opprettet_dato       TIMESTAMP NOT NULL ,
	opprettet_av         VARCHAR2(20) NOT NULL ,
	endret_dato          TIMESTAMP NULL ,
	endret_av            VARCHAR2(20) NULL 
);

CREATE UNIQUE INDEX XPKK_BEST_FAGSYSTEM ON K_BEST_FAGSYSTEM
(k_best_fagsystem   ASC);

ALTER TABLE K_BEST_FAGSYSTEM
	ADD CONSTRAINT  XPKK_BEST_FAGSYSTEM PRIMARY KEY (k_best_fagsystem);

CREATE TABLE K_BREV_PROD_APP
(
	k_brev_prod_app      VARCHAR2(20) NOT NULL , 
	dekode               VARCHAR2(200) NOT NULL ,
	opprettet_dato       TIMESTAMP NOT NULL ,
	opprettet_av         VARCHAR2(20) NOT NULL ,
	endret_dato          TIMESTAMP NULL ,
	endret_av            VARCHAR2(20) NULL 
);

CREATE UNIQUE INDEX XPKK_BREV_PROD_APP ON K_BREV_PROD_APP
(k_brev_prod_app   ASC);

ALTER TABLE K_BREV_PROD_APP
	ADD CONSTRAINT  XPKK_BREV_PROD_APP PRIMARY KEY (k_brev_prod_app);

CREATE TABLE K_DIST_KANAL
(
	k_dist_kanal         VARCHAR2(20) NOT NULL ,
	dekode               VARCHAR2(200) NOT NULL ,
	opprettet_dato       TIMESTAMP NOT NULL ,
	opprettet_av         VARCHAR2(20) NOT NULL ,
	endret_dato          TIMESTAMP NULL ,
	endret_av            VARCHAR2(20) NULL 
);

CREATE UNIQUE INDEX XPKK_DIST_KANAL ON K_DIST_KANAL
(k_dist_kanal   ASC);

ALTER TABLE K_DIST_KANAL
	ADD CONSTRAINT  XPKK_DIST_KANAL PRIMARY KEY (k_dist_kanal);

CREATE TABLE K_DIST_STATUS
(
	k_dist_status        VARCHAR2(20) NOT NULL ,
	dekode               VARCHAR2(200) NOT NULL ,
	opprettet_dato       TIMESTAMP NOT NULL ,
	opprettet_av         VARCHAR2(20) NOT NULL ,
	endret_dato          TIMESTAMP NULL ,
	endret_av            VARCHAR2(20) NULL 
);

CREATE UNIQUE INDEX XPKK_DIST_STATUS ON K_DIST_STATUS
(k_dist_status   ASC);

ALTER TABLE K_DIST_STATUS
	ADD CONSTRAINT  XPKK_DIST_STATUS PRIMARY KEY (k_dist_status);

CREATE TABLE K_DOKUMENT_STATUS
(
	k_dokument_status    VARCHAR2(20) NOT NULL ,
	dekode               VARCHAR2(200) NOT NULL ,
	opprettet_dato       TIMESTAMP NOT NULL ,
	opprettet_av         VARCHAR2(20) NOT NULL ,
	endret_dato          TIMESTAMP NULL ,
	endret_av            VARCHAR2(20) NULL 
);

CREATE UNIQUE INDEX XPKK_DOKUMENT_STATUS ON K_DOKUMENT_STATUS
(k_dokument_status   ASC);

ALTER TABLE K_DOKUMENT_STATUS
	ADD CONSTRAINT  XPKK_DOKUMENT_STATUS PRIMARY KEY (k_dokument_status);

CREATE TABLE K_FAGOMRADE
(
	k_fagomrade          VARCHAR2(20) NOT NULL ,
	dekode               VARCHAR2(200) NOT NULL ,
	opprettet_dato       TIMESTAMP NOT NULL ,
	opprettet_av         VARCHAR2(20) NOT NULL ,
	endret_dato          TIMESTAMP NULL ,
	endret_av            VARCHAR2(20) NULL 
);

CREATE UNIQUE INDEX XPKK_FAGOMRADE ON K_FAGOMRADE
(k_fagomrade   ASC);

ALTER TABLE K_FAGOMRADE
	ADD CONSTRAINT  XPKK_FAGOMRADE PRIMARY KEY (k_fagomrade);

CREATE TABLE K_FIL_STATUS
(
	dekode               VARCHAR2(200) NOT NULL ,
	opprettet_dato       TIMESTAMP NOT NULL ,
	opprettet_av         VARCHAR2(20) NOT NULL ,
	endret_dato          TIMESTAMP NULL ,
	endret_av            VARCHAR2(20) NULL ,
	k_fil_status         VARCHAR2(20) NOT NULL 
);

CREATE UNIQUE INDEX XPKK_FIL_STATUS ON K_FIL_STATUS
(k_fil_status   ASC);

ALTER TABLE K_FIL_STATUS
	ADD CONSTRAINT  XPKK_FIL_STATUS PRIMARY KEY (k_fil_status);

CREATE TABLE K_FIL_TYPE
(
	dekode               VARCHAR2(200) NOT NULL ,
	opprettet_dato       TIMESTAMP NOT NULL ,
	opprettet_av         VARCHAR2(20) NOT NULL ,
	endret_dato          TIMESTAMP NULL ,
	endret_av            VARCHAR2(20) NULL ,
	k_fil_type           VARCHAR2(20) NOT NULL 
);

CREATE UNIQUE INDEX XPKK_FIL_TYPE ON K_FIL_TYPE
(k_fil_type   ASC);

ALTER TABLE K_FIL_TYPE
	ADD CONSTRAINT  XPKK_FIL_TYPE PRIMARY KEY (k_fil_type);

CREATE TABLE K_KANAL_BEHANDLING
(
	k_kanal_behandling   VARCHAR2(20) NOT NULL ,
	dekode               VARCHAR2(200) NOT NULL ,
	opprettet_dato       TIMESTAMP NOT NULL ,
	opprettet_av         VARCHAR2(20) NOT NULL ,
	endret_dato          TIMESTAMP NULL ,
	endret_av            VARCHAR2(20) NULL 
);

CREATE UNIQUE INDEX XPKK_KANAL_BEHANDLING ON K_KANAL_BEHANDLING
(k_kanal_behandling   ASC);

ALTER TABLE K_KANAL_BEHANDLING
	ADD CONSTRAINT  XPKK_KANAL_BEHANDLING PRIMARY KEY (k_kanal_behandling);

CREATE TABLE K_KILDE_TYPE
(
	dekode               VARCHAR2(200) NOT NULL ,
	opprettet_dato       TIMESTAMP NOT NULL ,
	opprettet_av         VARCHAR2(20) NOT NULL ,
	endret_dato          TIMESTAMP NULL ,
	endret_av            VARCHAR2(20) NULL ,
	k_kilde_type         VARCHAR2(20) NOT NULL 
);

CREATE UNIQUE INDEX XPKK_KILDE_TYPE ON K_KILDE_TYPE
(k_kilde_type   ASC);

ALTER TABLE K_KILDE_TYPE
	ADD CONSTRAINT  XPKK_KILDE_TYPE PRIMARY KEY (k_kilde_type);

CREATE TABLE K_KOMM_RETNING
(
	dekode               VARCHAR2(200) NOT NULL ,
	opprettet_dato       TIMESTAMP NOT NULL ,
	opprettet_av         VARCHAR2(20) NOT NULL ,
	endret_dato          TIMESTAMP NULL ,
	endret_av            VARCHAR2(20) NULL ,
	k_komm_retning       VARCHAR2(20) NOT NULL 
);

CREATE UNIQUE INDEX XPKK_KOMM_RETNING ON K_KOMM_RETNING
(k_komm_retning   ASC);

ALTER TABLE K_KOMM_RETNING
	ADD CONSTRAINT  XPKK_KOMM_RETNING PRIMARY KEY (k_komm_retning);

CREATE TABLE K_MODUS
(
	k_modus              VARCHAR2(20) NOT NULL ,
	dekode               VARCHAR2(200) NOT NULL ,
	opprettet_dato       TIMESTAMP NOT NULL ,
	opprettet_av         VARCHAR2(20) NOT NULL ,
	endret_dato          TIMESTAMP NULL ,
	endret_av            VARCHAR2(20) NULL 
);

CREATE UNIQUE INDEX XPKK_MODUS ON K_MODUS
(k_modus   ASC);

ALTER TABLE K_MODUS
	ADD CONSTRAINT  XPKK_MODUS PRIMARY KEY (k_modus);

CREATE TABLE K_POST_DEST
(
	k_post_dest          VARCHAR2(20) NOT NULL ,
	dekode               VARCHAR2(200) NOT NULL ,
	opprettet_dato       TIMESTAMP NOT NULL ,
	opprettet_av         VARCHAR2(20) NOT NULL ,
	endret_dato          TIMESTAMP NULL ,
	endret_av            VARCHAR2(20) NULL 
);

CREATE UNIQUE INDEX XPKK_POST_DEST ON K_POST_DEST
(k_post_dest   ASC);

ALTER TABLE K_POST_DEST
	ADD CONSTRAINT  XPKK_POST_DEST PRIMARY KEY (k_post_dest);

ALTER TABLE DIST_INFO_FIL_INFO
	ADD (CONSTRAINT R_DIST_FIL FOREIGN KEY (distribusjon_info_id) REFERENCES DISTRIBUSJON_INFO (distribusjon_info_id));

ALTER TABLE DIST_INFO_FIL_INFO
	ADD (CONSTRAINT R_FIL_DIST FOREIGN KEY (fil_info_id) REFERENCES FIL_INFO (fil_info_id));

ALTER TABLE DISTRIBUSJON_INFO
	ADD (CONSTRAINT R_DIST_KANAL FOREIGN KEY (k_dist_kanal) REFERENCES K_DIST_KANAL (k_dist_kanal));

ALTER TABLE DISTRIBUSJON_INFO
	ADD (CONSTRAINT R_DIST_STATUS FOREIGN KEY (k_dist_status) REFERENCES K_DIST_STATUS (k_dist_status));

ALTER TABLE DISTRIBUSJON_INFO
	ADD (CONSTRAINT R_DIST_MODUS FOREIGN KEY (k_modus) REFERENCES K_MODUS (k_modus));

ALTER TABLE DISTRIBUSJON_INFO
	ADD (CONSTRAINT R_DIST_KANALB FOREIGN KEY (k_kanal_behandling) REFERENCES K_KANAL_BEHANDLING (k_kanal_behandling));

ALTER TABLE DISTRIBUSJON_INFO
	ADD (CONSTRAINT R_DIST_POST FOREIGN KEY (k_post_dest) REFERENCES K_POST_DEST (k_post_dest));

ALTER TABLE DOK_INFO_FIL_INFO
	ADD (CONSTRAINT R_DOK_FIL FOREIGN KEY (dokument_info_id) REFERENCES DOKUMENT_INFO (dokument_info_id));

ALTER TABLE DOK_INFO_FIL_INFO
	ADD (CONSTRAINT R_FIL_DOK FOREIGN KEY (fil_info_id) REFERENCES FIL_INFO (fil_info_id));

ALTER TABLE DOKUMENT_INFO
	ADD (CONSTRAINT R_DIST_DOK FOREIGN KEY (distribusjon_info_id) REFERENCES DISTRIBUSJON_INFO (distribusjon_info_id));

ALTER TABLE DOKUMENT_INFO
	ADD (CONSTRAINT R_DOK_STATUS FOREIGN KEY (k_dokument_status) REFERENCES K_DOKUMENT_STATUS (k_dokument_status));

ALTER TABLE DOKUMENT_INFO
	ADD (CONSTRAINT R_DOK_FAGOMRADE FOREIGN KEY (k_fagomrade) REFERENCES K_FAGOMRADE (k_fagomrade));

ALTER TABLE DOKUMENT_INFO
	ADD (CONSTRAINT R_DOK_FAGSYSTEM FOREIGN KEY (k_best_fagsystem) REFERENCES K_BEST_FAGSYSTEM (k_best_fagsystem));

ALTER TABLE DOKUMENT_INFO
	ADD (CONSTRAINT R_DOK_ARKIV FOREIGN KEY (k_arkiv_system) REFERENCES K_ARKIV_SYSTEM (k_arkiv_system));

ALTER TABLE DOKUMENT_INFO
	ADD (CONSTRAINT R_DOK_BREV_PROD FOREIGN KEY (k_brev_prod_app) REFERENCES K_BREV_PROD_APP (k_brev_prod_app));

ALTER TABLE FIL_INFO
	ADD (CONSTRAINT R_FIL_TYPE FOREIGN KEY (k_fil_type) REFERENCES K_FIL_TYPE (k_fil_type));

ALTER TABLE FIL_INFO
	ADD (CONSTRAINT R_FIL_RETNING FOREIGN KEY (k_komm_retning) REFERENCES K_KOMM_RETNING (k_komm_retning));

ALTER TABLE FIL_INFO
	ADD (CONSTRAINT R_FIL_STATUS FOREIGN KEY (k_fil_status) REFERENCES K_FIL_STATUS (k_fil_status));

ALTER TABLE FIL_INFO
	ADD (CONSTRAINT R_FIL_KILDE FOREIGN KEY (k_kilde_type) REFERENCES K_KILDE_TYPE (k_kilde_type));




-- Spring Batch oppsett, kopiert fra spring-batch-core.jar
CREATE TABLE BATCH_JOB_INSTANCE  (
	JOB_INSTANCE_ID NUMBER(19,0)  NOT NULL PRIMARY KEY ,
	VERSION NUMBER(19,0) ,
	JOB_NAME VARCHAR2(100) NOT NULL,
	JOB_KEY VARCHAR2(32) NOT NULL,
	constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
) ;

CREATE TABLE BATCH_JOB_EXECUTION  (
	JOB_EXECUTION_ID NUMBER(19,0)  NOT NULL PRIMARY KEY ,
	VERSION NUMBER(19,0)  ,
	JOB_INSTANCE_ID NUMBER(19,0) NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	START_TIME TIMESTAMP DEFAULT NULL ,
	END_TIME TIMESTAMP DEFAULT NULL ,
	STATUS VARCHAR2(10) ,
	EXIT_CODE VARCHAR2(100) ,
	EXIT_MESSAGE VARCHAR2(2500) ,
	LAST_UPDATED TIMESTAMP,
	constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
	references BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS  (
	JOB_EXECUTION_ID NUMBER(19,0) NOT NULL ,
	TYPE_CD VARCHAR2(6) NOT NULL ,
	KEY_NAME VARCHAR2(100) NOT NULL ,
	STRING_VAL VARCHAR2(250) ,
	DATE_VAL TIMESTAMP DEFAULT NULL ,
	LONG_VAL NUMBER(19,0) ,
	DOUBLE_VAL NUMBER ,
	IDENTIFYING CHAR(1) NOT NULL ,
	constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION  (
	STEP_EXECUTION_ID NUMBER(19,0)  NOT NULL PRIMARY KEY ,
	VERSION NUMBER(19,0) NOT NULL,
	STEP_NAME VARCHAR2(100) NOT NULL,
	JOB_EXECUTION_ID NUMBER(19,0) NOT NULL,
	START_TIME TIMESTAMP NOT NULL ,
	END_TIME TIMESTAMP DEFAULT NULL ,
	STATUS VARCHAR2(10) ,
	COMMIT_COUNT NUMBER(19,0) ,
	READ_COUNT NUMBER(19,0) ,
	FILTER_COUNT NUMBER(19,0) ,
	WRITE_COUNT NUMBER(19,0) ,
	READ_SKIP_COUNT NUMBER(19,0) ,
	WRITE_SKIP_COUNT NUMBER(19,0) ,
	PROCESS_SKIP_COUNT NUMBER(19,0) ,
	ROLLBACK_COUNT NUMBER(19,0) ,
	EXIT_CODE VARCHAR2(100) ,
	EXIT_MESSAGE VARCHAR2(2500) ,
	LAST_UPDATED TIMESTAMP,
	constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT  (
	STEP_EXECUTION_ID NUMBER(19,0) NOT NULL PRIMARY KEY,
	SHORT_CONTEXT VARCHAR2(2500) NOT NULL,
	SERIALIZED_CONTEXT CLOB ,
	constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
	references BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT  (
	JOB_EXECUTION_ID NUMBER(19,0) NOT NULL PRIMARY KEY,
	SHORT_CONTEXT VARCHAR2(2500) NOT NULL,
	SERIALIZED_CONTEXT CLOB ,
	constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NOCYCLE;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NOCYCLE;
CREATE SEQUENCE BATCH_JOB_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NOCYCLE;
