-- Dokumentdistribusjon_Kodeverk-100
insert into K_DIST_KANAL (k_dist_kanal,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('PRINT','Print',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_DIST_STATUS (k_dist_status,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('OPPRETTET','Opprettet',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_DIST_STATUS (k_dist_status,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('OVERSENDT','Oversendt',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_DIST_STATUS (k_dist_status,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('BEKREFTET','Bekreftet',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_DIST_STATUS (k_dist_status,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('FEILET','Feilet',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_MODUS (k_modus,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('P','Produksjon',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_MODUS (k_modus,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('T','Test',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_KANAL_BEHANDLING (k_kanal_behandling,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('A_C4_X_D_UP','A_C4_X_D_UP',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_KANAL_BEHANDLING (k_kanal_behandling,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('A_C5_X_D_UP','A_C5_X_D_UP',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_KANAL_BEHANDLING (k_kanal_behandling,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('A_C5_X_S_UP','A_C5_X_S_UP',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_KANAL_BEHANDLING (k_kanal_behandling,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('B_C5_X_D_UP','B_C5_X_D_UP',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_KANAL_BEHANDLING (k_kanal_behandling,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('A_VP','A_VP',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_KANAL_BEHANDLING (k_kanal_behandling,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('A_ZP','A_ZP',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_KANAL_BEHANDLING (k_kanal_behandling,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('A_ZPF','A_ZPF',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_KANAL_BEHANDLING (k_kanal_behandling,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('B_VP','B_VP',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_KANAL_BEHANDLING (k_kanal_behandling,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('B_ZP','B_ZP',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_POST_DEST (k_post_dest,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('INNLAND','Innland',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_POST_DEST (k_post_dest,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('UTLAND','Utland',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_DOKUMENT_STATUS (k_dokument_status,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('OPPRETTET','Opprettet',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_DOKUMENT_STATUS (k_dokument_status,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('OVERSENDT','Oversendt',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_DOKUMENT_STATUS (k_dokument_status,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('EKSPEDERT','Ekspedert',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_DOKUMENT_STATUS (k_dokument_status,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('FEILET','Feilet',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('BID','Bidrag',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('PEN','Pensjon',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('OVR','Øvrig',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('MOT','Skanning',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('OKO','Økonomi',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('BII','Bidrag innkreving',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('FS22','Gosys',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('BIL','Bil',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('HJE','Hjelpemidler',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('BAR','Barnetrygd',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('FOR','Foreldre- og svangerskapspenger',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('GRA','Gravferdsstønad',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('GRU','Grunn- og hjelpestønad',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('KON','Kontantstøtte',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('OMS','Omsorgspenger, Pleiepenger og opplæringspenger',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('SUP','Supplerende stønad',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('YRK','Yrkesskade / Menerstatning',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('ENF','Enslig forsørger',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('STO','Stønadsregnskap',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('FOS','Forsikring',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('ERS','Erstatning',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('SAK','Saksomkostning',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('DAG','Dagpenger',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('IND','Individstønad',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('MOB','Mobilitetsfremmende stønad',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('OPP','Oppfølging',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('VEN','Ventelønn',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('YRA','Yrkesrettet attføring',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('REH','Rehabilitering',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('UFO','Uføreytelser',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('SYK','Sykepenger',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('UKJ','Ukjent',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('FEI','Feilutbetaling (Arenaytelser)',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('KLA','Klage/Anke',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('GEN','Generell',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('AAP','Arbeidsavklaringspenger',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('FUL','Fullmakt',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('HEL','Helsetjenester og ort. hjelpemidler',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('CON','Condictio indebiti',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('MED','Medlemskap',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('SYM','Sykmelding',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('TIL','Tiltak',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('REK','Rekruttering og Stilling',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('IAR','Inkluderende arbeidsliv',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('AGR','Ajourhold - Grunnopplysninger',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('TRK','Trekk',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('KTR','Kontroll',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('PER','Permittering og masseoppsigelser',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('AAR','AA-registeret',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('TRY','Trygdeavgift',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('SAA','Sanksjon - Arbeidsgiver',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('SAP','Sanksjon - Person',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('OPA','Oppfølging',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FAGOMRADE (k_fagomrade,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('SER','Serviceklager',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BEST_FAGSYSTEM (k_best_fagsystem,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('UR','Ur',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BEST_FAGSYSTEM (k_best_fagsystem,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('INFOTRYGD','Infotrygd',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BEST_FAGSYSTEM (k_best_fagsystem,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('SYFO','Syfo',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BEST_FAGSYSTEM (k_best_fagsystem,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('KUHR','Kuhr',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BEST_FAGSYSTEM (k_best_fagsystem,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('KUHL','Kuhl',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BEST_FAGSYSTEM (k_best_fagsystem,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('ADHOC','Adhoc',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BEST_FAGSYSTEM (k_best_fagsystem,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('ELIN','Elin',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BEST_FAGSYSTEM (k_best_fagsystem,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('PREDATOR','Predator',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BEST_FAGSYSTEM (k_best_fagsystem,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('PESYS','Pesys',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BEST_FAGSYSTEM (k_best_fagsystem,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('BISYS','Bisys',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BEST_FAGSYSTEM (k_best_fagsystem,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('GOSYS','Gosys',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BEST_FAGSYSTEM (k_best_fagsystem,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('OEBS','Oebs',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_ARKIV_SYSTEM (k_arkiv_system,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('JOARK','Joark',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_ARKIV_SYSTEM (k_arkiv_system,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('MIDL_BREVLAGER','Midlertidig brevlager',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BREV_PROD_APP (k_brev_prod_app,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('UR_KORT','UR_KORT',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BREV_PROD_APP (k_brev_prod_app,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('UR_LANG','UR_LANG',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BREV_PROD_APP (k_brev_prod_app,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('UR_PTO','UR_PTO',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BREV_PROD_APP (k_brev_prod_app,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('INFOTRYGD','INFOTRYGD',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BREV_PROD_APP (k_brev_prod_app,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('UR_VLONN','UR_VLONN',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BREV_PROD_APP (k_brev_prod_app,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('SYFO_BBATCH','SYFO_BBATCH',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BREV_PROD_APP (k_brev_prod_app,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('SYFO_ONLBATCH','SYFO_ONLBATCH',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BREV_PROD_APP (k_brev_prod_app,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('KUHR_BREV','KUHR_BREV',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BREV_PROD_APP (k_brev_prod_app,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('KUHL_FRIKORT','KUHL_FRIKORT',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BREV_PROD_APP (k_brev_prod_app,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('ADHOC','ADHOC',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BREV_PROD_APP (k_brev_prod_app,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('ELIN_STANDARD','ELIN_STANDARD',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BREV_PROD_APP (k_brev_prod_app,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('ELIN_GIRO','ELIN_GIRO',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BREV_PROD_APP (k_brev_prod_app,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('ELIN_TREKKLISTE','ELIN_TREKKLISTE',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BREV_PROD_APP (k_brev_prod_app,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('ELIN_AAR','ELIN_AAR',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BREV_PROD_APP (k_brev_prod_app,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('PREDATOR_OB11','PREDATOR_OB11',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BREV_PROD_APP (k_brev_prod_app,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('PESYS_LBATCH','PESYS_LBATCH',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BREV_PROD_APP (k_brev_prod_app,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('PESYS_HBATCH','PESYS_HBATCH',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BREV_PROD_APP (k_brev_prod_app,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('BISYS_MND','BISYS_MND',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BREV_PROD_APP (k_brev_prod_app,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('BISYS_AAR','BISYS_AAR',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BREV_PROD_APP (k_brev_prod_app,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('GOSYS_DAG','GOSYS_DAG',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_BREV_PROD_APP (k_brev_prod_app,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('OEBS_FAKTURA','OEBS_FAKTURA',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FIL_STATUS (k_fil_status,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('OPPRETTET','Opprettet',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FIL_STATUS (k_fil_status,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('OK','OK',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FIL_STATUS (k_fil_status,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('FEILET','Feilet',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FIL_TYPE (k_fil_type,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('BEST_INFO_PRINT','Bestillingsinfo til print',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FIL_TYPE (k_fil_type,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('PRINTFIL','Printfil',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FIL_TYPE (k_fil_type,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('BEST_BEKR_PRINT','Bestillingsbekreftelse fra print',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FIL_TYPE (k_fil_type,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('DOK_RAPP_PRINT','Dokumentrapport fra print',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_FIL_TYPE (k_fil_type,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('AVSTEMMING_JOARK','Avstemming Joark',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_KILDE_TYPE (k_kilde_type,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('HP_REXX','HP Exstrean og REXX',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_KILDE_TYPE (k_kilde_type,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('SITS','SITS',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_KILDE_TYPE (k_kilde_type,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('DOKDIST','Dokumentdistribusjon',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_KOMM_RETNING (k_komm_retning,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('INNGAENDE','Inngående',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_KOMM_RETNING (k_komm_retning,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('UTGAENDE','Utgående',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
insert into K_KOMM_RETNING (k_komm_retning,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('INTERN','NAV intern',timestamp '2013-11-27 10:00:00','T. Fiksdal',NULL,NULL);
