ALTER TABLE DISTRIBUSJON_INFO MODIFY distribusjon_id VARCHAR2(40);

ALTER TABLE DOKUMENT_INFO MODIFY arkivkode VARCHAR2(40);


CREATE UNIQUE INDEX XAK1DISTRIBUSJON_INFO ON DISTRIBUSJON_INFO
(distribusjon_id   ASC);

ALTER TABLE DISTRIBUSJON_INFO
ADD CONSTRAINT  XAK1DISTRIBUSJON_INFO UNIQUE (distribusjon_id);


CREATE UNIQUE INDEX XAK1DOKUMENT_INFO ON DOKUMENT_INFO
(dokument_id   ASC);

ALTER TABLE DOKUMENT_INFO
ADD CONSTRAINT  XAK1DOKUMENT_INFO UNIQUE (dokument_id);


CREATE INDEX XIE1DOKUMENT_INFO ON DOKUMENT_INFO
(k_dokument_status   ASC,k_arkiv_system   ASC);