CREATE TABLE K_VARSEL_STATUS (
         K_VARSEL_STATUS	VARCHAR2(20 BYTE) NOT NULL PRIMARY KEY,
         DEKODE	VARCHAR2(200 BYTE)  NOT NULL,
         OPPRETTET_DATO	TIMESTAMP(6) NOT NULL,
         OPPRETTET_AV	VARCHAR2(20 BYTE) NOT NULL,
         ENDRET_DATO	TIMESTAMP(6),
         ENDRET_AV	VARCHAR2(20 BYTE)
);

ALTER TABLE DISTRIBUSJON_INFO ADD K_VARSEL_STATUS VARCHAR2(20 BYTE);

ALTER TABLE DISTRIBUSJON_INFO ADD CONSTRAINT XPKK_VARSEL_STATUS FOREIGN KEY (K_VARSEL_STATUS) REFERENCES K_VARSEL_STATUS(K_VARSEL_STATUS);

INSERT INTO K_VARSEL_STATUS (K_VARSEL_STATUS, DEKODE, OPPRETTET_DATO, OPPRETTET_AV) VALUES ('OPPRETTET', 'Varsel til mottaker er opprettet', sysdate, 'HÅKON SNØTUN');
INSERT INTO K_VARSEL_STATUS (K_VARSEL_STATUS, DEKODE, OPPRETTET_DATO, OPPRETTET_AV) VALUES ('FERDIGSTILT', 'Varsel til mottaker er ferdigstilt', sysdate, 'HÅKON SNØTUN');
INSERT INTO K_VARSEL_STATUS (K_VARSEL_STATUS, DEKODE, OPPRETTET_DATO, OPPRETTET_AV) VALUES ('FEILET', 'Varsel til mottaker har feilet', sysdate, 'HÅKON SNØTUN');