ALTER TABLE DISTRIBUSJON_INFO ADD (
    K_DISTRIBUSJONSTYPE varchar2(20) default null,
    K_DISTRIBUSJONSTIDSPUNKT varchar2(20) default null
);


CREATE TABLE K_DISTRIBUSJONSTYPE
(
    K_DISTRIBUSJONSTYPE VARCHAR2(20)  NOT NULL,
    dekode              VARCHAR2(200) NOT NULL,
    opprettet_dato      TIMESTAMP     NOT NULL,
    opprettet_av        VARCHAR2(20)  NOT NULL,
    endret_dato         TIMESTAMP     NULL,
    endret_av           VARCHAR2(20)  NULL
);

CREATE UNIQUE INDEX XPKK_DISTRIBUSJONSTYPE ON K_DISTRIBUSJONSTYPE
    (K_DISTRIBUSJONSTYPE ASC);

ALTER TABLE K_DISTRIBUSJONSTYPE
    ADD CONSTRAINT XPKK_DISTRIBUSJONSTYPE PRIMARY KEY (K_DISTRIBUSJONSTYPE);

CREATE INDEX XIF6DISTRIBUSJON_INFO ON DISTRIBUSJON_INFO
    (K_DISTRIBUSJONSTYPE ASC);

CREATE TABLE K_DISTRIBUSJONSTIDSPUNKT
(
    K_DISTRIBUSJONSTIDSPUNKT VARCHAR2(20)  NOT NULL,
    dekode                   VARCHAR2(200) NOT NULL,
    opprettet_dato           TIMESTAMP     NOT NULL,
    opprettet_av             VARCHAR2(20)  NOT NULL,
    endret_dato              TIMESTAMP     NULL,
    endret_av                VARCHAR2(20)  NULL
);

CREATE UNIQUE INDEX XPKK_DISTRIBUSJONSTIDSPUNKT ON K_DISTRIBUSJONSTIDSPUNKT
    (K_DISTRIBUSJONSTIDSPUNKT ASC);

ALTER TABLE K_DISTRIBUSJONSTIDSPUNKT
    ADD CONSTRAINT XPKK_DISTRIBUSJONSTIDSPUNKT PRIMARY KEY (K_DISTRIBUSJONSTIDSPUNKT);

CREATE INDEX XIF7DISTRIBUSJON_INFO ON DISTRIBUSJON_INFO
    (K_DISTRIBUSJONSTIDSPUNKT ASC);


insert into K_DISTRIBUSJONSTYPE (K_DISTRIBUSJONSTYPE,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('VEDTAK','VEDTAK',timestamp '2021-11-17 12:00:00','Tsigab A.',NULL,NULL);
insert into K_DISTRIBUSJONSTYPE (K_DISTRIBUSJONSTYPE,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('VIKTIG','VIKTIG',timestamp '2021-11-17 12:00:00','Tsigab A.',NULL,NULL);
insert into K_DISTRIBUSJONSTYPE (K_DISTRIBUSJONSTYPE,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('ANNET','ANNET',timestamp '2021-11-17 12:00:00','Tsigab A.',NULL,NULL);

insert into K_DISTRIBUSJONSTIDSPUNKT (K_DISTRIBUSJONSTIDSPUNKT,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('UMIDDELBART','UMIDDELBART',timestamp '2021-11-17 12:00:00','Tsigab A.',NULL,NULL);
insert into K_DISTRIBUSJONSTIDSPUNKT (K_DISTRIBUSJONSTIDSPUNKT,dekode,opprettet_dato,opprettet_av,endret_dato,endret_av) VALUES ('KJERNETID','KJERNETID',timestamp '2021-11-17 12:00:00','Tsigab A.',NULL,NULL);
