CREATE VIEW DVH_VARSEL_INFO
(VARSEL_INFO_ID, OPPRETTET_DATO, OPPRETTET_AV,
   ENDRET_DATO, ENDRET_AV, VERSJON,
   K_VARSLING_KANAL, VARSLINGSTEKST, EPOST_ADRESSE,
   MOBILTELEFON_NUMMER, ANTALL_REPETISJONER, DOKUMENT_INFO_ID)
AS
SELECT
VARSEL_INFO_ID, OPPRETTET_DATO, OPPRETTET_AV,
   ENDRET_DATO, ENDRET_AV, VERSJON,
   K_VARSLING_KANAL, VARSLINGSTEKST, EPOST_ADRESSE,
   MOBILTELEFON_NUMMER, ANTALL_REPETISJONER, DOKUMENT_INFO_ID
FROM VARSEL_INFO;
