CREATE VIEW DVH_DISTRIBUSJON_INFO
(DISTRIBUSJON_INFO_ID, DISTRIBUSJON_ID, AVTALE_REFERANSE,
   PRODUKSJON_DATO, DISTRIBUSJON_DATO, OPPRETTET_DATO,
   OPPRETTET_AV, ENDRET_DATO, ENDRET_AV,
   K_DIST_STATUS, K_MODUS, K_KANAL_BEHANDLING,
   K_POST_DEST, K_DIST_KANAL, VERSJON,
   EFF_TIDLIGST_DATO, EFF_SENEST_DATO, BEKR_MOTTATT_DATO,
   ORIGINAL_DISTRIBUSJON_ID, RESENDING_DISTRIBUSJON_ID)
AS
SELECT
DISTRIBUSJON_INFO_ID, DISTRIBUSJON_ID, AVTALE_REFERANSE,
   PRODUKSJON_DATO, DISTRIBUSJON_DATO, OPPRETTET_DATO,
   OPPRETTET_AV, ENDRET_DATO, ENDRET_AV,
   K_DIST_STATUS, K_MODUS, K_KANAL_BEHANDLING,
   K_POST_DEST, K_DIST_KANAL, VERSJON,
   EFF_TIDLIGST_DATO, EFF_SENEST_DATO, BEKR_MOTTATT_DATO,
   ORIGINAL_DISTRIBUSJON_ID, RESENDING_DISTRIBUSJON_ID
FROM DISTRIBUSJON_INFO;

CREATE VIEW DVH_FIL_INFO
(FIL_INFO_ID, FILNAVN, MOTTATT_DATO,
   SENDT_DATO, K_FIL_TYPE, K_KOMM_RETNING,
   K_FIL_STATUS, K_KILDE_TYPE, OPPRETTET_DATO,
   OPPRETTET_AV, ENDRET_DATO, ENDRET_AV,
   VERSJON)
AS
SELECT
FIL_INFO_ID, FILNAVN, MOTTATT_DATO,
   SENDT_DATO, K_FIL_TYPE, K_KOMM_RETNING,
   K_FIL_STATUS, K_KILDE_TYPE, OPPRETTET_DATO,
   OPPRETTET_AV, ENDRET_DATO, ENDRET_AV,
   VERSJON
FROM FIL_INFO;

CREATE VIEW DVH_DOKUMENT_INFO
(DOKUMENT_INFO_ID, DOKUMENT_ID, MOTTAKER_ID,
   ARKIVKODE, AVSTEMT_ARKIV_DATO, ANTALL_SIDER,
   ANTALL_ARK, OPPRETTET_DATO, OPPRETTET_AV,
   ENDRET_DATO, ENDRET_AV, DISTRIBUSJON_INFO_ID,
   K_DOKUMENT_STATUS, K_FAGOMRADE, K_BEST_FAGSYSTEM,
   K_ARKIV_SYSTEM, VERSJON, EKSPEDERT_DATO,
   MOTTAKER_NAVN, BREVKODE, K_BREV_PROD_APP,
   KONVERSASJON_ID, AVSENDER_ID, DIGITAL_DISTRIBUTOR_ID,
   DIGITAL_POSTKASSE_ADRESSE, APNINGSKVITTERING, VIRKNINGSDATO,
   K_SIKKERHETSNIVA, AAPNETDATO, POSTADRESSE_ID)
AS
SELECT
DOKUMENT_INFO_ID, DOKUMENT_ID, MOTTAKER_ID,
   ARKIVKODE, AVSTEMT_ARKIV_DATO, ANTALL_SIDER,
   ANTALL_ARK, OPPRETTET_DATO, OPPRETTET_AV,
   ENDRET_DATO, ENDRET_AV, DISTRIBUSJON_INFO_ID,
   K_DOKUMENT_STATUS, K_FAGOMRADE, K_BEST_FAGSYSTEM,
   K_ARKIV_SYSTEM, VERSJON, EKSPEDERT_DATO,
   MOTTAKER_NAVN, BREVKODE, K_BREV_PROD_APP,
   KONVERSASJON_ID, AVSENDER_ID, DIGITAL_DISTRIBUTOR_ID,
   DIGITAL_POSTKASSE_ADRESSE, APNINGSKVITTERING, VIRKNINGSDATO,
   K_SIKKERHETSNIVA, AAPNETDATO, POSTADRESSE_ID
FROM DOKUMENT_INFO;

CREATE VIEW DVH_DOKUMENT_REFERANSE
(OPPRETTET_DATO, OPPRETTET_AV, ENDRET_DATO,
   ENDRET_AV, VERSJON, DOKUMENT_REFERANSE_ID,
   DOKUMENT_INFO_ID, K_REFERERER_TIL, DOKUMENT_URI,
   FIL_STORRELSE)
AS
SELECT
OPPRETTET_DATO, OPPRETTET_AV, ENDRET_DATO,
   ENDRET_AV, VERSJON, DOKUMENT_REFERANSE_ID,
   DOKUMENT_INFO_ID, K_REFERERER_TIL, DOKUMENT_URI,
   FIL_STORRELSE
FROM DOKUMENT_REFERANSE;

CREATE VIEW DVH_POSTADRESSE
(POSTADRESSE_ID, ADRESSELINJE1, ADRESSELINJE2,
   ADRESSELINJE3, POSTNUMMER, POSTSTED,
   K_LANDKODE, OPPRETTET_DATO, OPPRETTET_AV,
   ENDRET_DATO, ENDRET_AV, VERSJON)
AS
SELECT
POSTADRESSE_ID, ADRESSELINJE1, ADRESSELINJE2,
   ADRESSELINJE3, POSTNUMMER, POSTSTED,
   K_LANDKODE, OPPRETTET_DATO, OPPRETTET_AV,
   ENDRET_DATO, ENDRET_AV, VERSJON
FROM POSTADRESSE;

-- VARSEL_INFO er ny i HL4-2016

/*
CREATE VIEW DVH_VARSEL_INFO
(VARSEL_INFO_ID, OPPRETTET_DATO, OPPRETTET_AV,
   ENDRET_DATO, ENDRET_AV, VERSJON,
   K_VARSLING_KANAL, VARSLINGSTEKST, EPOST_ADRESSE,
   MOBILTELEFON_NUMMER, ANTALL_REPETISJONER, DOKUMENT_INFO_ID)
AS
SELECT
VARSEL_INFO_ID, OPPRETTET_DATO, OPPRETTET_AV,
   ENDRET_DATO, ENDRET_AV, VERSJON,
   K_VARSLING_KANAL, VARSLINGSTEKST, EPOST_ADRESSE,
   MOBILTELEFON_NUMMER, ANTALL_REPETISJONER, DOKUMENT_INFO_ID
FROM VARSEL_INFO;
*/

CREATE VIEW DVH_FEILKVITTERING
(FEILKVITTERING_ID, K_FEIL_TYPE, FEILPART,
   DETALJER, FEILET_TIDSPUNKT, VERSJON,
   DOKUMENT_INFO_ID, OPPRETTET_DATO, OPPRETTET_AV,
   ENDRET_DATO, ENDRET_AV)
AS
SELECT
FEILKVITTERING_ID, K_FEIL_TYPE, FEILPART,
   DETALJER, FEILET_TIDSPUNKT, VERSJON,
   DOKUMENT_INFO_ID, OPPRETTET_DATO, OPPRETTET_AV,
   ENDRET_DATO, ENDRET_AV
FROM FEILKVITTERING;

-- Koblingstabell mellom DISTRIBUSJON_INFO og FIL_INFO

CREATE VIEW DVH_DIST_INFO_FIL_INFO
(DISTRIBUSJON_INFO_ID, FIL_INFO_ID)
AS
SELECT
DISTRIBUSJON_INFO_ID, FIL_INFO_ID
FROM DIST_INFO_FIL_INFO;

-- Koblingstabell mellom DOKUMENT_INFO og FIL_INFO

CREATE VIEW DVH_DOK_INFO_FIL_INFO
(DOKUMENT_INFO_ID, FIL_INFO_ID)
AS
SELECT
DOKUMENT_INFO_ID, FIL_INFO_ID
FROM DOK_INFO_FIL_INFO;


-- KODEVERK
CREATE VIEW DVH_K_ARKIV_SYSTEM
(K_ARKIV_SYSTEM, DEKODE, OPPRETTET_DATO,
      OPPRETTET_AV, ENDRET_DATO, ENDRET_AV)
AS
SELECT
K_ARKIV_SYSTEM, DEKODE, OPPRETTET_DATO,
   OPPRETTET_AV, ENDRET_DATO, ENDRET_AV
FROM K_ARKIV_SYSTEM;

CREATE VIEW DVH_K_BEST_FAGSYSTEM
(K_BEST_FAGSYSTEM, DEKODE, OPPRETTET_DATO,
      OPPRETTET_AV, ENDRET_DATO, ENDRET_AV)
AS
SELECT
K_BEST_FAGSYSTEM, DEKODE, OPPRETTET_DATO,
   OPPRETTET_AV, ENDRET_DATO, ENDRET_AV
FROM K_BEST_FAGSYSTEM;

CREATE VIEW DVH_K_BREV_PROD_APP
(K_BREV_PROD_APP, DEKODE, OPPRETTET_DATO,
      OPPRETTET_AV, ENDRET_DATO, ENDRET_AV)
AS
SELECT
K_BREV_PROD_APP, DEKODE, OPPRETTET_DATO,
   OPPRETTET_AV, ENDRET_DATO, ENDRET_AV
FROM K_BREV_PROD_APP;

CREATE VIEW DVH_K_DIST_KANAL
(K_DIST_KANAL, DEKODE, OPPRETTET_DATO,
      OPPRETTET_AV, ENDRET_DATO, ENDRET_AV)
AS
SELECT
K_DIST_KANAL, DEKODE, OPPRETTET_DATO,
   OPPRETTET_AV, ENDRET_DATO, ENDRET_AV
FROM K_DIST_KANAL;

CREATE VIEW DVH_K_DIST_STATUS
(K_DIST_STATUS, DEKODE, OPPRETTET_DATO,
      OPPRETTET_AV, ENDRET_DATO, ENDRET_AV)
AS
SELECT
K_DIST_STATUS, DEKODE, OPPRETTET_DATO,
   OPPRETTET_AV, ENDRET_DATO, ENDRET_AV
FROM K_DIST_STATUS;

CREATE VIEW DVH_K_DOKUMENT_STATUS
(K_DOKUMENT_STATUS, DEKODE, OPPRETTET_DATO,
      OPPRETTET_AV, ENDRET_DATO, ENDRET_AV)
AS
SELECT
K_DOKUMENT_STATUS, DEKODE, OPPRETTET_DATO,
   OPPRETTET_AV, ENDRET_DATO, ENDRET_AV
FROM K_DOKUMENT_STATUS;

CREATE VIEW DVH_K_FAGOMRADE
(K_FAGOMRADE, DEKODE, OPPRETTET_DATO,
      OPPRETTET_AV, ENDRET_DATO, ENDRET_AV)
AS
SELECT
K_FAGOMRADE, DEKODE, OPPRETTET_DATO,
   OPPRETTET_AV, ENDRET_DATO, ENDRET_AV
FROM K_FAGOMRADE;

CREATE VIEW DVH_K_FEIL_TYPE
(K_FEIL_TYPE, DEKODE, OPPRETTET_DATO,
      OPPRETTET_AV, ENDRET_DATO, ENDRET_AV)
AS
SELECT
K_FEIL_TYPE, DEKODE, OPPRETTET_DATO,
   OPPRETTET_AV, ENDRET_DATO, ENDRET_AV
FROM K_FEIL_TYPE;

CREATE VIEW DVH_K_FIL_STATUS
(DEKODE, OPPRETTET_DATO, OPPRETTET_AV,
      ENDRET_DATO, ENDRET_AV, K_FIL_STATUS)
AS
SELECT
DEKODE, OPPRETTET_DATO, OPPRETTET_AV,
   ENDRET_DATO, ENDRET_AV, K_FIL_STATUS
FROM K_FIL_STATUS;

CREATE VIEW DVH_K_FIL_TYPE
(DEKODE, OPPRETTET_DATO, OPPRETTET_AV,
      ENDRET_DATO, ENDRET_AV, K_FIL_TYPE)
AS
SELECT
DEKODE, OPPRETTET_DATO, OPPRETTET_AV,
   ENDRET_DATO, ENDRET_AV, K_FIL_TYPE
FROM K_FIL_TYPE;

CREATE VIEW DVH_K_KANAL_BEHANDLING
(K_KANAL_BEHANDLING, DEKODE, OPPRETTET_DATO,
      OPPRETTET_AV, ENDRET_DATO, ENDRET_AV)
AS
SELECT
K_KANAL_BEHANDLING, DEKODE, OPPRETTET_DATO,
   OPPRETTET_AV, ENDRET_DATO, ENDRET_AV
FROM K_KANAL_BEHANDLING;

CREATE VIEW DVH_K_KILDE_TYPE
(DEKODE, OPPRETTET_DATO, OPPRETTET_AV,
      ENDRET_DATO, ENDRET_AV, K_KILDE_TYPE)
AS
SELECT
DEKODE, OPPRETTET_DATO, OPPRETTET_AV,
   ENDRET_DATO, ENDRET_AV, K_KILDE_TYPE
FROM K_KILDE_TYPE;

CREATE VIEW DVH_K_KOMM_RETNING
(DEKODE, OPPRETTET_DATO, OPPRETTET_AV,
      ENDRET_DATO, ENDRET_AV, K_KOMM_RETNING)
AS
SELECT
DEKODE, OPPRETTET_DATO, OPPRETTET_AV,
   ENDRET_DATO, ENDRET_AV, K_KOMM_RETNING
FROM K_KOMM_RETNING;

CREATE VIEW DVH_K_LANDKODE_POST_DEST
(K_LANDKODE, POST_DEST, OPPRETTET_DATO,
      OPPRETTET_AV, ENDRET_DATO, ENDRET_AV)
AS
SELECT
K_LANDKODE, POST_DEST, OPPRETTET_DATO,
   OPPRETTET_AV, ENDRET_DATO, ENDRET_AV
FROM K_LANDKODE_POST_DEST;

CREATE VIEW DVH_K_MODUS
(K_MODUS, DEKODE, OPPRETTET_DATO,
      OPPRETTET_AV, ENDRET_DATO, ENDRET_AV)
AS
SELECT
K_MODUS, DEKODE, OPPRETTET_DATO,
   OPPRETTET_AV, ENDRET_DATO, ENDRET_AV
FROM K_MODUS;

CREATE VIEW DVH_K_POST_DEST
(K_POST_DEST, DEKODE, OPPRETTET_DATO,
      OPPRETTET_AV, ENDRET_DATO, ENDRET_AV)
AS
SELECT
K_POST_DEST, DEKODE, OPPRETTET_DATO,
   OPPRETTET_AV, ENDRET_DATO, ENDRET_AV
FROM K_POST_DEST;

CREATE VIEW DVH_K_REFERERER_TIL
(K_REFERERER_TIL, DEKODE, OPPRETTET_DATO,
      OPPRETTET_AV, ENDRET_DATO, ENDRET_AV)
AS
SELECT
K_REFERERER_TIL, DEKODE, OPPRETTET_DATO,
   OPPRETTET_AV, ENDRET_DATO, ENDRET_AV
FROM K_REFERERER_TIL;

CREATE VIEW DVH_K_SIKKERHETSNIVA
(K_SIKKERHETSNIVA, DEKODE, OPPRETTET_DATO,
      OPPRETTET_AV, ENDRET_DATO, ENDRET_AV)
AS
SELECT
K_SIKKERHETSNIVA, DEKODE, OPPRETTET_DATO,
   OPPRETTET_AV, ENDRET_DATO, ENDRET_AV
FROM K_SIKKERHETSNIVA;

CREATE VIEW DVH_K_VARSLING_KANAL
(K_VARSLING_KANAL, DEKODE, OPPRETTET_DATO,
      OPPRETTET_AV, ENDRET_DATO, ENDRET_AV)
AS
SELECT
K_VARSLING_KANAL, DEKODE, OPPRETTET_DATO,
   OPPRETTET_AV, ENDRET_DATO, ENDRET_AV
FROM K_VARSLING_KANAL;