INSERT INTO K_LANDKODE_POST_DEST (K_LANDKODE, POST_DEST, OPPRETTET_DATO, OPPRETTET_AV)
  SELECT
    'XK',
    'EUROPA',
    TIMESTAMP '2016-03-07 10:00:00.000000',
    'Andreas Skomedal'
  FROM dual
  WHERE NOT exists(SELECT *
                   FROM K_LANDKODE_POST_DEST
                   WHERE K_LANDKODE = 'XK');
