CREATE OR REPLACE VIEW DVH_DOKUMENT_INFO
(DOKUMENT_INFO_ID, DOKUMENT_ID, MOTTAKER_ID,
    ARKIVKODE, AVSTEMT_ARKIV_DATO, ANTALL_SIDER,
    ANTALL_ARK, OPPRETTET_DATO, OPPRETTET_AV,
    ENDRET_DATO, ENDRET_AV, DISTRIBUSJON_INFO_ID,
    K_DOKUMENT_STATUS, K_FAGOMRADE, K_BEST_FAGSYSTEM,
    K_ARKIV_SYSTEM, VERSJON, EKSPEDERT_DATO,
    MOTTAKER_NAVN, BREVKODE, K_BREV_PROD_APP,
    KONVERSASJON_ID, AVSENDER_ID, DIGITAL_DISTRIBUTOR_ID,
    DIGITAL_POSTKASSE_ADRESSE, APNINGSKVITTERING, VIRKNINGSDATO,
    K_SIKKERHETSNIVA, AAPNETDATO, POSTADRESSE_ID, K_MOTTAKER_ID_TYPE, FORSENDELSE_TITTEL, BATCH_ID)
  AS
    SELECT
           DOKUMENT_INFO_ID, DOKUMENT_ID, MOTTAKER_ID,
           ARKIVKODE, AVSTEMT_ARKIV_DATO, ANTALL_SIDER,
           ANTALL_ARK, OPPRETTET_DATO, OPPRETTET_AV,
           ENDRET_DATO, ENDRET_AV, DISTRIBUSJON_INFO_ID,
           K_DOKUMENT_STATUS, K_FAGOMRADE, K_BEST_FAGSYSTEM,
           K_ARKIV_SYSTEM, VERSJON, EKSPEDERT_DATO,
           MOTTAKER_NAVN, BREVKODE, K_BREV_PROD_APP,
           KONVERSASJON_ID, AVSENDER_ID, DIGITAL_DISTRIBUTOR_ID,
           DIGITAL_POSTKASSE_ADRESSE, APNINGSKVITTERING, VIRKNINGSDATO,
           K_SIKKERHETSNIVA, AAPNETDATO, POSTADRESSE_ID, K_MOTTAKER_ID_TYPE,
           FORSENDELSE_TITTEL, BATCH_ID
    FROM DOKUMENT_INFO;